### ISSUE TITLE
Error on world load, due to malformed recipe json.

### ISSUE THREAD

**Issue by canitzp** [AstralOrdana/Mores-Forge#3]
Like the title says, one recipe file is malformed.
In this line https://github.com/AstralOrdana/Mores-Forge/blob/main/src/main/resources/data/mores/recipes/crushing/diorite_emerald_ore.json#L13 a comma i missing, making the whole json unreadable.

> [17:31:37] [Worker-Main-12/ERROR]: Couldn't parse data file mores:crushing/diorite_emerald_ore from mores:recipes/crushing/diorite_emerald_ore.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 14 column 8 path $.results[1].item
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:52) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:20) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 14 column 8 path $.results[1].item
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:490) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:725) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:726) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[gson-2.8.8.jar%2325!/:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:908) ~[gson-2.8.8.jar%2325!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[client-1.18.1-20211210.034407-srg.jar%23291!/:?]
	... 11 more

**Comment by AstralOrdana** [comment]
fixed
